name: Core
version: '${project.version}'
main: mcup.core.Core
api-version: 1.18
authors: [ GoracioNewport ]
description: Core plugin for basic functions handling
depend: [ PlaceholderAPI, LuckPerms, ProtocolLib ]
commands:
  core:
    description: Admin tool for managing MCup core
